baseURL = 'https://photos.sowrey.org/'
languageCode = 'en-us'
title = 'One Thousand Words: Photos by Geoff Sowrey'
copyright = "© {year} Geoff Sowrey"
theme = "paper"
pluralizelisttitles = "false"
canonifyURLs = true
timeout=60

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 70
  resampleFilter = 'Lanczos'

params.author.name = 'Geoff Sowrey'

[params]
  description = 'Photography by Geoff Sowrey'

  # color style
  color = 'linen'                           # linen, wheat, gray, light

  dateFormat = "02 January 2006 15:04"

  # header social icons
  twitter = 'sowrey'               # twitter.com/YOUR_TWITTER_ID
  github = 'gsowrey'                 # github.com/YOUR_GITHUB_ID
  instagram = 'sowrey'           # instagram.com/YOUR_INSTAGRAM_ID
  mastodon = 'https://mastodon.social/@sowrey'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

[pagination]
  paginate = 100
  path='photos'
