# deploy.yml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          #hugo-version: 'latest'
          hugo-version: '0.119.0'
          extended: true

      - name: Install NPM Modules
        run: npm install

      - name: Library versions
        run: |
          go version
          node -v

      - name: Create Image Data Files
        run: node build_library.js

      - name: Create Hugo Content Pages
        run: node hugo.js generate

      - name: Check for missing _index.md files
        run: node check_index.js

      - name: Hugo Build
        run: hugo --minify

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_PAGES_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: 'photos-sowrey-org'
          directory: ./public
          branch: ''
          gitHubToken: ${{ secrets.DEPLOY_TOKEN }}

      - name: Clear Homepage Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/d6dbf9fee9e34912b868bd87c2fdbc89/purge_cache" \
            -H "X-Auth-Email: geoff@sowrey.org" \
            -H "X-Auth-Key: 1296c3226f102a98835d19e4d491bf77d034f" \
            -H "Content-Type: application/json" \
            --data '{"files":["https://photos.sowrey.org/","https://photos.sowrey.org/photos/","https://photos.sowrey.org/sitemap.xml","https://photos.sowrey.org/robots.txt"]}'
