# development.yml
name: Staging

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install NPM Modules
        run: npm install

      - name: Create Image Data Files
        run: node build_library.js

      - name: Create Hugo Content Pages
        run: node hugo.js generate

      - name: Check for missing _index.md files
        run: node check_index.js

      - name: Hugo Build
        run: hugo --minify

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_PAGES_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: 'photos-sowrey-org'
          directory: ./public
          branch: ''
          gitHubToken: ${{ secrets.DEPLOY_TOKEN }}

